export default {
    SHOP_DOMAIN: 'shop.piletilevi.ee',
    DEFAULT_SEAT_HOVER_COLOR: '#27272e',
    DEFAULT_SEAT_ACTIVE_COLOR: '#27272e',
    DEFAULT_SEAT_INACTIVE_COLOR: '#d0d0d0',
    DEFAULT_SEAT_BUFFERED_COLOR: '#ffffff',
    DEFAULT_SEAT_BUFFERED_BORDER_COLOR: '#d0d0d0',
    SEAT_CIRCLE_RADIUS: 6,
    STAGE_TEXT_SIZE: 20,
    DEBUG_FULL_PLACESMAP_SECTIONS: false,
};